// <auto-generated />
using System;
using FinanceTracker.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceTrackerDbContext))]
    partial class FinanceTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ExpensesPlanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResetInterval")
                        .HasColumnType("int");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpensesPlanners");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveThisMonth")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RegularIncome")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.SavingGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOfMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavingGoals");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpensesPlannerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SavingGoalId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionSource")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserMonthlyBudgetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpensesPlannerId");

                    b.HasIndex("SavingGoalId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMonthlyBudgetId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.UserMonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMonthlyBudgets");
                });

            modelBuilder.Entity("IncomeUserMonthlyBudget", b =>
                {
                    b.Property<int>("IncomesId")
                        .HasColumnType("int");

                    b.Property<int>("UserMonthlyBudgetsId")
                        .HasColumnType("int");

                    b.HasKey("IncomesId", "UserMonthlyBudgetsId");

                    b.HasIndex("UserMonthlyBudgetsId");

                    b.ToTable("IncomeUserMonthlyBudget");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ExpensesPlanner", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.ExchangeRate", "OriginalExchangeRate", b1 =>
                        {
                            b1.Property<int>("ExpensesPlannerId")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Mid")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ExpensesPlannerId");

                            b1.ToTable("ExpensesPlanners");

                            b1.WithOwner()
                                .HasForeignKey("ExpensesPlannerId");
                        });

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.Category", "Category", b1 =>
                        {
                            b1.Property<int>("ExpensesPlannerId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ExpensesPlannerId");

                            b1.ToTable("ExpensesPlanners");

                            b1.WithOwner()
                                .HasForeignKey("ExpensesPlannerId");
                        });

                    b.Navigation("Category");

                    b.Navigation("OriginalExchangeRate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Income", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.ExchangeRate", "OriginalExchangeRate", b1 =>
                        {
                            b1.Property<int>("IncomeId")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Mid")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("IncomeId");

                            b1.ToTable("Incomes");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.Navigation("OriginalExchangeRate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.SavingGoal", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.ExchangeRate", "OriginalExchangeRate", b1 =>
                        {
                            b1.Property<int>("SavingGoalId")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Mid")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("SavingGoalId");

                            b1.ToTable("SavingGoals");

                            b1.WithOwner()
                                .HasForeignKey("SavingGoalId");
                        });

                    b.Navigation("OriginalExchangeRate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.ExpensesPlanner", "ExpensesPlanner")
                        .WithMany("Transactions")
                        .HasForeignKey("ExpensesPlannerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceTracker.Domain.Entities.SavingGoal", "SavingGoal")
                        .WithMany("Transactions")
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinanceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceTracker.Domain.Entities.UserMonthlyBudget", "UserMonthlyBudget")
                        .WithMany()
                        .HasForeignKey("UserMonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.ExchangeRate", "ExchangeRate", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Mid")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("ExchangeRate");

                    b.Navigation("ExpensesPlanner");

                    b.Navigation("SavingGoal");

                    b.Navigation("User");

                    b.Navigation("UserMonthlyBudget");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.UserMonthlyBudget", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FinanceTracker.Domain.Entities.Owned.ExchangeRate", "OriginalExchangeRate", b1 =>
                        {
                            b1.Property<int>("UserMonthlyBudgetId")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Mid")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("UserMonthlyBudgetId");

                            b1.ToTable("UserMonthlyBudgets");

                            b1.WithOwner()
                                .HasForeignKey("UserMonthlyBudgetId");
                        });

                    b.Navigation("OriginalExchangeRate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IncomeUserMonthlyBudget", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.Income", null)
                        .WithMany()
                        .HasForeignKey("IncomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceTracker.Domain.Entities.UserMonthlyBudget", null)
                        .WithMany()
                        .HasForeignKey("UserMonthlyBudgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ExpensesPlanner", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.SavingGoal", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
